package com.todociber.appbolsadevalores.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.todociber.appbolsadevalores.db.Cedeval;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table CEDEVAL.
*/
public class CedevalDao extends AbstractDao<Cedeval, Long> {

    public static final String TABLENAME = "CEDEVAL";

    /**
     * Properties of entity Cedeval.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property IdCuenta = new Property(1, String.class, "idCuenta", false, "ID_CUENTA");
        public final static Property NumeroDeCuenta = new Property(2, String.class, "NumeroDeCuenta", false, "NUMERO_DE_CUENTA");
        public final static Property IdCliente = new Property(3, String.class, "idCliente", false, "ID_CLIENTE");
    };


    public CedevalDao(DaoConfig config) {
        super(config);
    }
    
    public CedevalDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'CEDEVAL' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'ID_CUENTA' TEXT," + // 1: idCuenta
                "'NUMERO_DE_CUENTA' TEXT," + // 2: NumeroDeCuenta
                "'ID_CLIENTE' TEXT);"); // 3: idCliente
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'CEDEVAL'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Cedeval entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String idCuenta = entity.getIdCuenta();
        if (idCuenta != null) {
            stmt.bindString(2, idCuenta);
        }
 
        String NumeroDeCuenta = entity.getNumeroDeCuenta();
        if (NumeroDeCuenta != null) {
            stmt.bindString(3, NumeroDeCuenta);
        }
 
        String idCliente = entity.getIdCliente();
        if (idCliente != null) {
            stmt.bindString(4, idCliente);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Cedeval readEntity(Cursor cursor, int offset) {
        Cedeval entity = new Cedeval( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // idCuenta
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // NumeroDeCuenta
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // idCliente
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Cedeval entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIdCuenta(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setNumeroDeCuenta(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIdCliente(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Cedeval entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Cedeval entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
