package com.todociber.appbolsadevalores.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.todociber.appbolsadevalores.db.Emisores;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table EMISORES.
*/
public class EmisoresDao extends AbstractDao<Emisores, Long> {

    public static final String TABLENAME = "EMISORES";

    /**
     * Properties of entity Emisores.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property IdEmisor = new Property(1, String.class, "idEmisor", false, "ID_EMISOR");
        public final static Property NombreEmisor = new Property(2, String.class, "nombreEmisor", false, "NOMBRE_EMISOR");
        public final static Property IdTitulo = new Property(3, String.class, "idTitulo", false, "ID_TITULO");
    };


    public EmisoresDao(DaoConfig config) {
        super(config);
    }
    
    public EmisoresDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'EMISORES' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'ID_EMISOR' TEXT," + // 1: idEmisor
                "'NOMBRE_EMISOR' TEXT," + // 2: nombreEmisor
                "'ID_TITULO' TEXT);"); // 3: idTitulo
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'EMISORES'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Emisores entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String idEmisor = entity.getIdEmisor();
        if (idEmisor != null) {
            stmt.bindString(2, idEmisor);
        }
 
        String nombreEmisor = entity.getNombreEmisor();
        if (nombreEmisor != null) {
            stmt.bindString(3, nombreEmisor);
        }
 
        String idTitulo = entity.getIdTitulo();
        if (idTitulo != null) {
            stmt.bindString(4, idTitulo);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Emisores readEntity(Cursor cursor, int offset) {
        Emisores entity = new Emisores( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // idEmisor
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // nombreEmisor
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // idTitulo
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Emisores entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIdEmisor(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setNombreEmisor(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIdTitulo(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Emisores entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Emisores entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
