package com.todociber.appbolsadevalores.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table EMISORES.
 */
public class Emisores {

    private Long id;
    private String idEmisor;
    private String nombreEmisor;
    private String idTitulo;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Emisores() {
    }

    public Emisores(Long id) {
        this.id = id;
    }

    public Emisores(Long id, String idEmisor, String nombreEmisor, String idTitulo) {
        this.id = id;
        this.idEmisor = idEmisor;
        this.nombreEmisor = nombreEmisor;
        this.idTitulo = idTitulo;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIdEmisor() {
        return idEmisor;
    }

    public void setIdEmisor(String idEmisor) {
        this.idEmisor = idEmisor;
    }

    public String getNombreEmisor() {
        return nombreEmisor;
    }

    public void setNombreEmisor(String nombreEmisor) {
        this.nombreEmisor = nombreEmisor;
    }

    public String getIdTitulo() {
        return idTitulo;
    }

    public void setIdTitulo(String idTitulo) {
        this.idTitulo = idTitulo;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
