package com.todociber.appbolsadevalores.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table CASAS_CORREDORAS.
 */
public class CasasCorredoras {

    private Long id;
    private String idCasa;
    private String NombreCasa;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public CasasCorredoras() {
    }

    public CasasCorredoras(Long id) {
        this.id = id;
    }

    public CasasCorredoras(Long id, String idCasa, String NombreCasa) {
        this.id = id;
        this.idCasa = idCasa;
        this.NombreCasa = NombreCasa;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIdCasa() {
        return idCasa;
    }

    public void setIdCasa(String idCasa) {
        this.idCasa = idCasa;
    }

    public String getNombreCasa() {
        return NombreCasa;
    }

    public void setNombreCasa(String NombreCasa) {
        this.NombreCasa = NombreCasa;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
