package com.todociber.appbolsadevalores.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table CEDEVAL.
 */
public class Cedeval {

    private Long id;
    private String idCuenta;
    private String NumeroDeCuenta;
    private String idCliente;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Cedeval() {
    }

    public Cedeval(Long id) {
        this.id = id;
    }

    public Cedeval(Long id, String idCuenta, String NumeroDeCuenta, String idCliente) {
        this.id = id;
        this.idCuenta = idCuenta;
        this.NumeroDeCuenta = NumeroDeCuenta;
        this.idCliente = idCliente;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIdCuenta() {
        return idCuenta;
    }

    public void setIdCuenta(String idCuenta) {
        this.idCuenta = idCuenta;
    }

    public String getNumeroDeCuenta() {
        return NumeroDeCuenta;
    }

    public void setNumeroDeCuenta(String NumeroDeCuenta) {
        this.NumeroDeCuenta = NumeroDeCuenta;
    }

    public String getIdCliente() {
        return idCliente;
    }

    public void setIdCliente(String idCliente) {
        this.idCliente = idCliente;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
