package com.todociber.appbolsadevalores.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.todociber.appbolsadevalores.db.TokenPush;
import com.todociber.appbolsadevalores.db.Emisores;
import com.todociber.appbolsadevalores.db.TipoMercado;
import com.todociber.appbolsadevalores.db.Titulos;
import com.todociber.appbolsadevalores.db.Cliente;
import com.todociber.appbolsadevalores.db.Cedeval;
import com.todociber.appbolsadevalores.db.CasasCorredoras;
import com.todociber.appbolsadevalores.db.Ordenes;
import com.todociber.appbolsadevalores.db.OrdenesPadre;
import com.todociber.appbolsadevalores.db.Mensajes;
import com.todociber.appbolsadevalores.db.OperacionesBolsa;

import com.todociber.appbolsadevalores.db.TokenPushDao;
import com.todociber.appbolsadevalores.db.EmisoresDao;
import com.todociber.appbolsadevalores.db.TipoMercadoDao;
import com.todociber.appbolsadevalores.db.TitulosDao;
import com.todociber.appbolsadevalores.db.ClienteDao;
import com.todociber.appbolsadevalores.db.CedevalDao;
import com.todociber.appbolsadevalores.db.CasasCorredorasDao;
import com.todociber.appbolsadevalores.db.OrdenesDao;
import com.todociber.appbolsadevalores.db.OrdenesPadreDao;
import com.todociber.appbolsadevalores.db.MensajesDao;
import com.todociber.appbolsadevalores.db.OperacionesBolsaDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tokenPushDaoConfig;
    private final DaoConfig emisoresDaoConfig;
    private final DaoConfig tipoMercadoDaoConfig;
    private final DaoConfig titulosDaoConfig;
    private final DaoConfig clienteDaoConfig;
    private final DaoConfig cedevalDaoConfig;
    private final DaoConfig casasCorredorasDaoConfig;
    private final DaoConfig ordenesDaoConfig;
    private final DaoConfig ordenesPadreDaoConfig;
    private final DaoConfig mensajesDaoConfig;
    private final DaoConfig operacionesBolsaDaoConfig;

    private final TokenPushDao tokenPushDao;
    private final EmisoresDao emisoresDao;
    private final TipoMercadoDao tipoMercadoDao;
    private final TitulosDao titulosDao;
    private final ClienteDao clienteDao;
    private final CedevalDao cedevalDao;
    private final CasasCorredorasDao casasCorredorasDao;
    private final OrdenesDao ordenesDao;
    private final OrdenesPadreDao ordenesPadreDao;
    private final MensajesDao mensajesDao;
    private final OperacionesBolsaDao operacionesBolsaDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tokenPushDaoConfig = daoConfigMap.get(TokenPushDao.class).clone();
        tokenPushDaoConfig.initIdentityScope(type);

        emisoresDaoConfig = daoConfigMap.get(EmisoresDao.class).clone();
        emisoresDaoConfig.initIdentityScope(type);

        tipoMercadoDaoConfig = daoConfigMap.get(TipoMercadoDao.class).clone();
        tipoMercadoDaoConfig.initIdentityScope(type);

        titulosDaoConfig = daoConfigMap.get(TitulosDao.class).clone();
        titulosDaoConfig.initIdentityScope(type);

        clienteDaoConfig = daoConfigMap.get(ClienteDao.class).clone();
        clienteDaoConfig.initIdentityScope(type);

        cedevalDaoConfig = daoConfigMap.get(CedevalDao.class).clone();
        cedevalDaoConfig.initIdentityScope(type);

        casasCorredorasDaoConfig = daoConfigMap.get(CasasCorredorasDao.class).clone();
        casasCorredorasDaoConfig.initIdentityScope(type);

        ordenesDaoConfig = daoConfigMap.get(OrdenesDao.class).clone();
        ordenesDaoConfig.initIdentityScope(type);

        ordenesPadreDaoConfig = daoConfigMap.get(OrdenesPadreDao.class).clone();
        ordenesPadreDaoConfig.initIdentityScope(type);

        mensajesDaoConfig = daoConfigMap.get(MensajesDao.class).clone();
        mensajesDaoConfig.initIdentityScope(type);

        operacionesBolsaDaoConfig = daoConfigMap.get(OperacionesBolsaDao.class).clone();
        operacionesBolsaDaoConfig.initIdentityScope(type);

        tokenPushDao = new TokenPushDao(tokenPushDaoConfig, this);
        emisoresDao = new EmisoresDao(emisoresDaoConfig, this);
        tipoMercadoDao = new TipoMercadoDao(tipoMercadoDaoConfig, this);
        titulosDao = new TitulosDao(titulosDaoConfig, this);
        clienteDao = new ClienteDao(clienteDaoConfig, this);
        cedevalDao = new CedevalDao(cedevalDaoConfig, this);
        casasCorredorasDao = new CasasCorredorasDao(casasCorredorasDaoConfig, this);
        ordenesDao = new OrdenesDao(ordenesDaoConfig, this);
        ordenesPadreDao = new OrdenesPadreDao(ordenesPadreDaoConfig, this);
        mensajesDao = new MensajesDao(mensajesDaoConfig, this);
        operacionesBolsaDao = new OperacionesBolsaDao(operacionesBolsaDaoConfig, this);

        registerDao(TokenPush.class, tokenPushDao);
        registerDao(Emisores.class, emisoresDao);
        registerDao(TipoMercado.class, tipoMercadoDao);
        registerDao(Titulos.class, titulosDao);
        registerDao(Cliente.class, clienteDao);
        registerDao(Cedeval.class, cedevalDao);
        registerDao(CasasCorredoras.class, casasCorredorasDao);
        registerDao(Ordenes.class, ordenesDao);
        registerDao(OrdenesPadre.class, ordenesPadreDao);
        registerDao(Mensajes.class, mensajesDao);
        registerDao(OperacionesBolsa.class, operacionesBolsaDao);
    }
    
    public void clear() {
        tokenPushDaoConfig.getIdentityScope().clear();
        emisoresDaoConfig.getIdentityScope().clear();
        tipoMercadoDaoConfig.getIdentityScope().clear();
        titulosDaoConfig.getIdentityScope().clear();
        clienteDaoConfig.getIdentityScope().clear();
        cedevalDaoConfig.getIdentityScope().clear();
        casasCorredorasDaoConfig.getIdentityScope().clear();
        ordenesDaoConfig.getIdentityScope().clear();
        ordenesPadreDaoConfig.getIdentityScope().clear();
        mensajesDaoConfig.getIdentityScope().clear();
        operacionesBolsaDaoConfig.getIdentityScope().clear();
    }

    public TokenPushDao getTokenPushDao() {
        return tokenPushDao;
    }

    public EmisoresDao getEmisoresDao() {
        return emisoresDao;
    }

    public TipoMercadoDao getTipoMercadoDao() {
        return tipoMercadoDao;
    }

    public TitulosDao getTitulosDao() {
        return titulosDao;
    }

    public ClienteDao getClienteDao() {
        return clienteDao;
    }

    public CedevalDao getCedevalDao() {
        return cedevalDao;
    }

    public CasasCorredorasDao getCasasCorredorasDao() {
        return casasCorredorasDao;
    }

    public OrdenesDao getOrdenesDao() {
        return ordenesDao;
    }

    public OrdenesPadreDao getOrdenesPadreDao() {
        return ordenesPadreDao;
    }

    public MensajesDao getMensajesDao() {
        return mensajesDao;
    }

    public OperacionesBolsaDao getOperacionesBolsaDao() {
        return operacionesBolsaDao;
    }

}
