package com.todociber.appbolsadevalores.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table OPERACIONES_BOLSA.
 */
public class OperacionesBolsa {

    private Long id;
    private String idOperacion;
    private String montoOperacion;
    private String idOrden;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public OperacionesBolsa() {
    }

    public OperacionesBolsa(Long id) {
        this.id = id;
    }

    public OperacionesBolsa(Long id, String idOperacion, String montoOperacion, String idOrden) {
        this.id = id;
        this.idOperacion = idOperacion;
        this.montoOperacion = montoOperacion;
        this.idOrden = idOrden;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIdOperacion() {
        return idOperacion;
    }

    public void setIdOperacion(String idOperacion) {
        this.idOperacion = idOperacion;
    }

    public String getMontoOperacion() {
        return montoOperacion;
    }

    public void setMontoOperacion(String montoOperacion) {
        this.montoOperacion = montoOperacion;
    }

    public String getIdOrden() {
        return idOrden;
    }

    public void setIdOrden(String idOrden) {
        this.idOrden = idOrden;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
