package com.todociber.appbolsadevalores.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table TOKEN_PUSH.
 */
public class TokenPush {

    private Long id;
    private String tokenPush;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public TokenPush() {
    }

    public TokenPush(Long id) {
        this.id = id;
    }

    public TokenPush(Long id, String tokenPush) {
        this.id = id;
        this.tokenPush = tokenPush;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTokenPush() {
        return tokenPush;
    }

    public void setTokenPush(String tokenPush) {
        this.tokenPush = tokenPush;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
